description: Id không trùng khớp với sản phẩm nào
content:
  application/json:
    schema:
      properties:
        message:
          title: Thông báo ngắn
          type: string
          description: Không có kết quả truy vấn nào cho mô hình [App\Models\Product] 76
          example: No query results for model [App\Models\Product] 76
      type: object