get:
  description: "Lấy danh sách sản phẩm (Chỉ hiển thị sản phẩm enabled: 'true', visibility: 'Catalog/ Catalog và Tìm kiếm' và tối thiểu 1 sản phẩm option có status: 'Còn hàng')"
  tags:
    - Sản phẩm
  parameters:
    - name: search
      in: path
      description: Từ khoá tìm kiếm sản phẩm
      example: Sh mode
  responses:
    200:
      description: Lấy danh sách sản phẩm thành công
      content:
        application/json:
          schema:
            properties:
              data:
                title: Dữ liệu
                example:
                  - id: 76
                    name: Sh mode
                    description: Thuộc phân khúc xe ga cao cấp và thừa hưởng thiết kế sang trọng nổi tiếng của dòng xe SH, Sh mode luôn được đánh giá cao nhờ kiểu dáng sang trọng, tinh tế tới từng đường nét, động cơ tiên tiến và các tiện nghi cao cấp xứng tầm phong cách sống thời thượng, đẳng cấp.
                    min_price:
                      raw: 161105278.00
                      preview: 161.105.278,00 VND
                    max_price:
                      raw: 968519527.76
                      preview: 968.519.527,76 VND
                    images:
                      - image: https://localhost:8000/storage/product/d100d8f7ac62cc4743d57b6900bb895a.png
                        alt: Et temporibus provident qui qui.
                    videos:
                      - image: d100d8f7ac62cc4743d57b6900bb895a.png
                        title: Aut beatae quas eum id minima.
                        description: Sed dolorem ut saepe enim. Pariatur et amet provident laboriosam. Dignissimos veritatis dolorem soluta commodi. Soluta excepturi quod veritatis. Accusantium repellendus cupiditate neque eligendi et ut iste. Recusandae non possimus aut reiciendis.
                        video:
                          provider: youtube
                          id: e1811b11-43d6-3c9c-906f-b16ce611bd87
                          url: https://www.youtube.com/watch?v=e1811b11-43d6-3c9c-906f-b16ce611bd87
                    enabled: true
                    visibility: Catalog
                    specifications:
                      - key: Pariatur nam deleniti sit molestiae fugiat.
                        value: Aperiam voluptas aut sapiente perspiciatis impedit. Ut rem est minima eum ut quidem. Nostrum eaque porro sed delectus.
                    options:
                      - id: 1
                        sku: DK5UDS2WUT_RED_STANDARD
                        price: 161105278.00
                        price_preview: 161.105.278,00 VND
                        images:
                          - image: https://localhost:8000/storage/product/d100d8f7ac62cc4743d57b6900bb895a.png
                            alt: Et temporibus provident qui qui.
                        color: Đỏ
                        version: Tiêu chuẩn
                        status: Còn hàng
                        type: Sản phẩm tân trang
                        quantity: 12939
                        weight: 139
                        specifications:
                          - key: Pariatur nam deleniti sit molestiae fugiat.
                            value: Aperiam voluptas aut sapiente perspiciatis impedit. Ut rem est minima eum ut quidem. Nostrum eaque porro sed delectus.
                        product_id: 3
                        created_at: 11:53:58 21/06/2024
                        updated_at: 11:53:58 21/06/2024
                    categories:
                      - id: 1
                        name: Xe tay ga
                        pivot:
                          product_id: 76
                          category_id: 1
                        deleted_at: 11:53:58 21/06/2024
                        created_at: 11:53:58 21/06/2024
                        updated_at:
                          11:53:58 21/06/2024
                    deleted_at: 11:53:58 21/06/2024
                    created_at: 11:53:58 21/06/2024
                    updated_at: 11:53:58 21/06/2024
                type: array
              total_pages:
                title: Tổng trang
                example: 7
                type: number
              from:
                title: Vị trí dữ liệu đầu tiên của trang
                example: 76
                type: number
              to:
                title: Vị trí dữ liệu cuối cùng của trang
                example: 90
                type: number
              per_page:
                title: Tổng dữ liệu mỗi trang
                example: 15
                type: number
              current_page:
                title: Vị trí trang hiện tại
                example: 6
                type: number
              total:
                title: Tổng dữ liệu
                example: 100
                type: number
            type: object